version: '3'
services:
  # greetings
  greeting1:
    build: ./
    volumes:
      - ./:/go/src/lecture-app
    restart: always
    environment:
      GREETING_MESSAGE: Hello
      PORT: ':3000'
  greeting2:
    build: ./
    volumes:
      - ./:/go/src/lecture-app
    restart: always
    environment:
      GREETING_MESSAGE: こんにちは
      PORT: ':3001'

  # nginx
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
