version: '3'
services:
  greeting:
    build: ./
    volumes:
      - ./:/go/src/lecture-app
    restart: always
    environment:
      GREETING_MESSAGE: Hello
      PORT: ':3000'
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
